//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea2Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PracticaLNEntities : DbContext
    {
        public PracticaLNEntities()
            : base("name=PracticaLNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Vehiculos> Vehiculos { get; set; }
    
        public virtual ObjectResult<ConsultarVehiculos_Result> ConsultarVehiculos(string matricula, Nullable<decimal> precioInicial, Nullable<int> fabricacion)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("Matricula", matricula) :
                new ObjectParameter("Matricula", typeof(string));
    
            var precioInicialParameter = precioInicial.HasValue ?
                new ObjectParameter("PrecioInicial", precioInicial) :
                new ObjectParameter("PrecioInicial", typeof(decimal));
    
            var fabricacionParameter = fabricacion.HasValue ?
                new ObjectParameter("Fabricacion", fabricacion) :
                new ObjectParameter("Fabricacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ConsultarVehiculos_Result>("ConsultarVehiculos", matriculaParameter, precioInicialParameter, fabricacionParameter);
        }
    }
}
